alicat_device:
  ros__parameters:
    device_serial_number: FT4U1ID2
    flowrate_topic: alicat_device/flowrate
    flowrate_service: alicat_device/set_flow_rate

second_alicat_device:
  ros__parameters:
    device_serial_number: FT4TF9NT
    flowrate_topic: second_alicat_device/flowrate
    flowrate_service: second_alicat_device/set_flow_rate

alicat_client:
  ros__parameters:
    flowrate_topic: alicat_device/flowrate
    flowrate_service: alicat_device/set_flow_rate

second_alicat_client:
  ros__parameters:
    flowrate_topic: second_alicat_device/flowrate
    flowrate_service: second_alicat_device/set_flow_rate
